# Generated by Django 5.1.7 on 2025-04-01 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_category_remove_article_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='email',
        ),
    ]
